#Prefix change
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Convenient split binds
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# QOL enhancements
set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set -g set-clipboard on
set -g update-environment "WAYLAND_DISPLAY DISPLAY"
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

# vim-style selection-yank
set -g mode-keys vi
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'alexwforsythe/tmux-which-key'

#Catppuccin
set -g @catppuccin_flavour 'mocha'

#Continuum
set -g @continuum-restore 'on'
set -g @continuum-boot 'off'

# TPM INIT
run  '~/.tmux/plugins/tpm/tpm'
